fix the build with NOPORTDOCS
Installing rubygem-iobuffer-1.1.2... done
===>  Staging for rubygem-cool.io-1.1.1
===>   rubygem-cool.io-1.1.1 depends on package: rubygem-iobuffer>=1.0.0
- found
===>   rubygem-cool.io-1.1.1 depends on file: /usr/local/bin/gem21 -
found
===>   rubygem-cool.io-1.1.1 depends on file: /usr/local/bin/ruby21 -
found
===>   Generating temporary packing list
Building native extensions.  This could take a while...
ERROR:  While generating documentation for cool.io-1.1.1
... MESSAGE:   missing aref_prefix for RDoc::SingleClass
... RDOC args: --op
/work/a/ports/devel/rubygem-cool.io/work/stage/usr/local/lib/ruby/gems/2.1/doc/cool.io-1.1.1/rdoc
lib --title cool.io-1.1.1 Documentation --quiet
Successfully installed cool.io-1.1.1
1 gem installed
Installing RDoc documentation for cool.io-1.1.1...
*** Error code 1

Stop.
make[1]: stopped in /a/ports/devel/rubygem-cool.io